config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :subs
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end

  resources :comments, only: [:create, :show]

  root to: "subs#index"
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  content    :string           not null
#  author_id  :integer          not null
#  post_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ActiveRecord::Base
  validates :content, :author, :post, presence: true

  belongs_to :author,
    foreign_key: :author_id,
    class_name: :User

  belongs_to :post

  belongs_to :parent_comment,
    foreign_key: :parent_comment_id,
    class_name: :Comment

  has_many :child_comments,
    foreign_key: :parent_comment_id,
    class_name: :Comment
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id

    if @comment.save
      redirect_to post_url(@comment.post_id)
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to new_post_comment_url(@comment.post_id)
    end
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/new.html.erb
<h1>New Comment</h1>

<form action="<%= comments_url %>" method="POST">
  <%= auth_token %>
  <input type="hidden" name="comment[post_id]" value="<%= params[:post_id] %>" />

  <label>Content:
    <input type="text" name="comment[content]" id="Content" value="<%= @comment.content %>" />
  </label>
  <br />

  <input type="submit" value="Create New Comment" />
</form>

app/views/comments/show.html.erb
<h1>Comment</h1>

<%= @comment.content %>
<br>
By <%= @comment.author.username %>
<br>
<br>

Add Comment

<form action="<%= comments_url %>" method="POST">
  <%= auth_token %>

  <input type="hidden" name="comment[parent_comment_id]" value="<%= @comment.id %>" />
  <input type="hidden" name="comment[post_id]" value="<%= @comment.post_id %>" />

  <label>Content:
    <input type="text" name="comment[content]" id="Content" value="" />
  </label>
  <br />

  <input type="submit" value="Create New Comment" />
</form>