config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :subs
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end

  resources :comments, only: [:create, :show]

  root to: "subs#index"
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :string           not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :title, :moderator, presence: true
  validates :title, uniqueness: true

  belongs_to :moderator,
    foreign_key: :moderator_id,
    class_name: :User

  has_many :post_subs, dependent: :destroy, inverse_of: :sub,
    foreign_key: :sub_id,
    class_name: :PostSub

  has_many :posts,
    through: :post_subs,
    source: :post


end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_filter :require_login!, only: [:new, :create]
  before_action :require_moderator!, only: [:edit, :update]
  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = current_user.subs.find(params[:id])

    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def require_moderator!
    unless current_user.subs.ids.include?(params[:id].to_i)
      flash[:errors] = ['You have no permission to do this']
      redirect_to subs_url
    end
  end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<form action="<%= sub_url(@sub) %>" method="POST">
  <input type="hidden" name="_method" value="PATCH" />
  <%= auth_token %>

  <label>Title:
    <input type="text" name="sub[title]" id="Title" value="<%= @sub.title %>" />
  </label>
  <br />

  <label>Description:
    <input type="text" name="sub[description]" id="Description"  value="<%= @sub.description %>" />
  </label>
  <br />

  <input type="submit" value="Update Sub" />
</form>

app/views/subs/index.html.erb
<h1>All Subs</h1>

<%= link_to "Add Sub", new_sub_url %>
<br />
<br />
<br />

<ul>
<% @subs.each do |sub| %>
  <li>
    <%= link_to sub.title, sub_url(sub) %>
  </li>
<% end %>
</ul>

app/views/subs/new.html.erb
<h1>New Sub</h1>

<form action="<%= subs_url %>" method="POST">
  <%= auth_token %>

  <label>Title:
    <input type="text" name="sub[title]" id="Title" value="<%= @sub.title %>" />
  </label>
  <br />

  <label>Description:
    <input type="text" name="sub[description]" id="Description"  value="<%= @sub.description %>" />
  </label>
  <br />

  <input type="submit" value="Create New Sub" />
</form>

app/views/subs/show.html.erb
<h1>Sub</h1>

<%= link_to "All subs", subs_url %>
<br />
<br />

Title: <%= @sub.title %>
<br />
<br />
Description: <%= @sub.description %>
<br />
<br />
Moderator: <%= @sub.moderator.username %>
<br />
<br />
<br />

<%= link_to "Edit Sub", edit_sub_url(@sub) %>
<br />
<br />
<%= link_to "Add Post", new_post_url + "?sub_id=#{@sub.id}" %>
<br />
<br />

All Posts
<ul>
<% @sub.posts.each do |post| %>
  <li>
    <%= link_to post.title, post_url(post) %>
  </li>
<% end %>
</ul>