config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :subs
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end

  resources :comments, only: [:create, :show]

  root to: "subs#index"
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string           not null
#  content    :string           not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  validates :title, :author, presence: true

  validate :require_sub

  belongs_to :author,
    foreign_key: :author_id,
    class_name: :User

  has_many :post_subs, dependent: :destroy, inverse_of: :post,
    foreign_key: :post_id,
    class_name: :PostSub

  has_many :subs,
    through: :post_subs,
    source: :sub

  has_many :comments, dependent: :destroy

  def comments_by_parent_id
    result = Hash.new { |h, k| h[k] = [] }

    self.comments.includes(:author).all.each do |comment|
      result[comment.parent_comment_id] << comment
    end

    result
  end

  private

  def require_sub
    if self.subs.length <= 0
      errors[:subs] << "Require at least 1 sub"
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_login!, only: [:new, :create]
  before_action :require_author!, only: [:edit, :update, :destroy]
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id

    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])

    @comments_by_parent_id = @post.comments_by_parent_id
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])

    unless @post.destroy
      flash[:errors] = @post.errors.full_messages
    end

    redirect_to sub_url(@post.sub_id)
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end

  def require_author!
    unless current_user.posts.ids.include?(params[:id].to_i)
      flash[:errors] = ['You have no permission to do this']
      redirect_to root_url
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<li>
  <%= comment.content %>
  <br />
  By <%= comment.author.username %>
  <br />
  <%= link_to "Detail", comment_url(comment) %>
  <br />
  <br />

  <ul>
    <% @comments_by_parent_id[comment.id].each do |child| %>
    <%= render "comment", comment: child  %>
    <% end %>
  </ul>
</li>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<form action="<%= post_url(@post) %>" method="POST">
  <input type="hidden" name="_method" value="PATCH" />
  <%= auth_token %>

  <label>Title:
    <input type="text" name="post[title]" id="Title" value="<%= @post.title %>" />
  </label>
  <br />

  <label>URL:
    <input type="text" name="post[url]" id="URL"  value="<%= @post.url %>" />
  </label>
  <br />

  <label>Content:
    <input type="text" name="post[content]" id="Content"  value="<%= @post.content %>" />
  </label>
  <br />

  <input type="hidden" name="post[sub_ids][]" value="" />
  <label>Subs:</label>
  <br />
  <% Sub.all.each do |sub| %>
    <label>
      <input
        type="checkbox"
        name="post[sub_ids][]"
        value="<%= sub.id %>"
        <%= "checked='checked'" if @post.sub_ids.include?(sub.id) %>
        />
      <%= sub.title %>
      <br />
    </label>
  <% end %>


  <input type="submit" value="Update Post" />
</form>

app/views/posts/new.html.erb
<h1>New Post</h1>

<form action="<%= posts_url %>" method="POST">
  <%= auth_token %>

  <label>Title:
    <input type="text" name="post[title]" id="Title" value="<%= @post.title %>" />
  </label>
  <br />

  <label>URL:
    <input type="text" name="post[url]" id="URL"  value="<%= @post.url %>" />
  </label>
  <br />

  <label>Content:
    <input type="text" name="post[content]" id="Content"  value="<%= @post.content %>" />
  </label>
  <br />

  <input type="hidden" name="post[sub_ids][]" value="" />
  <label>Subs:</label>
  <br />
  <% Sub.all.each do |sub| %>
    <label>
      <input
        type="checkbox"
        name="post[sub_ids][]"
        value="<%= sub.id %>"
        <%= "checked='checked'" if @post.sub_ids.include?(sub.id) %>
        />
      <%= sub.title %>
      <br />
    </label>
  <% end %>

  <input type="submit" value="Create New Post" />
</form>

app/views/posts/show.html.erb
<h1>Post</h1>

<%= @post.title %>
<br />
<br />
<%= link_to @post.url, @post.url %>
<br />
<br />
<%= @post.content %>
<br />
<br />
<br />
Subs:
<br />
<ul>
<% @post.subs.each do |sub| %>
  <li>
    <%= link_to sub.title, sub_url(sub) %>
  </li>
<% end %>
</ul>

<%= link_to "Edit Post", edit_post_url(@post) %>
<br />
<br />
<%= button_to "Delete Post", post_url(@post), method: :delete %>
<br />
<br />
<br />

Comments
<br />
<br />
<%= link_to "Add Comment", new_post_comment_url(@post) %>
<br />
<br />

<ul>
  <% @comments_by_parent_id[nil].each do |comment| %>
    <%= render "comment", comment: comment %>
  <% end %>
</ul>